apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-persista-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: go-persista
  endpoints:
  - port: http
    path: /metrics
